### ISSUE TITLE
streams and buffers do not work as input

### ISSUE THREAD

**Issue by pps83** [Intervox/node-webp#15] opened 2018-01-04 16:33 UTC
CWebp does not accept streams or buffers as input, contrary to [what documentation says](https://www.npmjs.com/package/cwebp#available-source-types):

sample code:
```
var fs = require('fs');
var gm = require('gm');
var CWebp = require('cwebp').CWebp;


function test(fl){
	var img = gm(fl);
	img
	.fill("#000000")
	.stroke("#000000", 1)
	.drawRectangle(0, 0, 10, 10)
	.toBuffer('PNG', function(err, buffer){
		if (!err)
		{
			fs.writeFileSync(fl + '-2.png', buffer); // this is OK
			// This fails: (however, var encoder = new CWebp(fl + '-2.png');
			var encoder = new CWebp(buffer);
			encoder.quality(75).toBuffer().then(function(buffer){
				var out = fs.createWriteStream(fl+'-xx.webp');
				out.write(buffer);
				out.end(() =>{
					console.log('file path:', fl+'.webp');
				});
			});
		}
	});
}

test('someimage.png');
```

and this is the error output:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:867:14)
```

It works if I save that buffer first to a file and then create CWebp using that written file.

**Comment by lbeschastny** [comment] 2018-01-04 22:41
I've just tried your code sample and it worked fine. It produced correct webp image `someimage.png-xx.webp` in a current working directory.

Could you add some more information about your problem and environment?

Since youd didn't provide your `someimage.png`, I've used [sample png image from wikipedia][1] instead.

Here is my environment:

```sh
$ node -v
v8.4.0

$ npm -v
5.2.0

$ npm ls --depth=0
├── cwebp@2.0.2
└── gm@1.23.1

$ gm -version
GraphicsMagick 1.3.23 2015-11-07 Q16 http://www.GraphicsMagick.org/
Host type: x86_64-pc-linux-gnu
```

[1]: https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png

**Comment by lbeschastny** [comment] 2018-01-04 22:51
Here is the minimal buffer usage example:

```js
let fs = require('fs')
let CWebp = require('cwebp').CWebp

function test (filename, outname) {
  let buffer = fs.readFileSync(filename)
  let encoder = new CWebp(buffer)
  encoder.quality(75).write(outname, function (err) {
    console.log(err || outname)
  })
}

test('someimage.png', 'out.webp')
```

Please, try it in your environment.

**Comment by lbeschastny** [comment] 2018-01-04 22:53
I'm closing this issue for now since I can't reproduce the problem.

**Closed by lbeschastny** 2018-01-04 22:53 UTC
Labels: can't reproduce
